### ISSUE TITLE
what will be the "Enter the URL end-point of your server."

### ISSUE THREAD

**Issue by Sjnahak** [greenido/jfrog-xray-2-slack-example#16]
confused what will be  the URL end-point of your server.
example in the doc is https://greenido.wordpress.com/2020/03/30/integrate-jfrog-xray-with-slack/ 
https://xray-2-slack.glitch.me/xray/api/

Did not work and we didn't receive any alert in slack

Step followed:
1. clone the repo in  our agent server
2. edited .env file and passed the slack hook url
3. in jfrog we created the webhook 

let us know what we are missing here ?

**Comment by greenido** [comment]
The server I used for the example is here: https://xray-2-slack.glitch.me/xray/api/

You should change it to the URL of your server.
Good luck.

**Comment by Sjnahak** [comment]
Closing the since I implemented using below
https://jfrog.com/knowledge-base/how-to-send-xray-security-and-license-violation-messages-to-slack/#:~:text=Xray%20has%20the%20Webhook%20integration,one%20are%20different%20as%20below.&text=%7B%20%22text%22%3A%20%22Hello,Sending%20messages%20using%20Incoming%20Webhooks.
